# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kkr13\OneDrive\Desktop\final year project\Final_Year\FacesTrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(608, 367)
        Form.setMinimumSize(QtCore.QSize(608, 367))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(140, 180, 355, 52))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectXml = QtWidgets.QPushButton(self.frame)
        self.selectXml.setObjectName("selectXml")
        self.horizontalLayout.addWidget(self.selectXml)
        self.trainBtn = QtWidgets.QPushButton(self.frame)
        self.trainBtn.setObjectName("trainBtn")
        self.horizontalLayout.addWidget(self.trainBtn)
        self.selectDir = QtWidgets.QPushButton(self.frame)
        self.selectDir.setObjectName("selectDir")
        self.horizontalLayout.addWidget(self.selectDir)
        self.progressFrame = QtWidgets.QFrame(Form)
        self.progressFrame.setGeometry(QtCore.QRect(50, 250, 521, 51))
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.trainProgress = QtWidgets.QProgressBar(self.progressFrame)
        self.trainProgress.setGeometry(QtCore.QRect(30, 10, 481, 23))
        self.trainProgress.setProperty("value", 0)
        self.trainProgress.setObjectName("trainProgress")
        self.doneFrame = QtWidgets.QFrame(Form)
        self.doneFrame.setGeometry(QtCore.QRect(50, 310, 501, 41))
        self.doneFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.doneFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.doneFrame.setObjectName("doneFrame")
        self.trainingDone = QtWidgets.QTextEdit(self.doneFrame)
        self.trainingDone.setGeometry(QtCore.QRect(200, 0, 121, 31))
        self.trainingDone.setObjectName("trainingDone")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 70, 161, 111))
        self.label.setMinimumSize(QtCore.QSize(161, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/pyhton icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectXml.setText(_translate("Form", "SELECT XML"))
        self.trainBtn.setText(_translate("Form", "TRAIN"))
        self.selectDir.setText(_translate("Form", "SELECT DIR"))
        self.trainingDone.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">Training Done</span></p></body></html>"))
import pyqt_design
